# Generated by Django 4.2.5 on 2023-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_answer_score_currentgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
