# Generated by Django 4.2.5 on 2023-09-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_answer_score_questions_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ans',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
